app = "botcuatam250k"
build = { }
primary_region = "sin"

[http_service]
auto_start_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 1
processes = [ "app" ]

[[vm]]
size = "performance-16x"